server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:mysql://172.16.2.12:3306/db_usuarios
    username: root
    password: 1234

# Actualiza a�adiendo columnas pero no regenera la tabla
  jpa:
    hibernate:
      ddl-auto: update


# Cuando hay cambios, elimina la tabla y datos, y la vuelve a crear
# spring.jpa.hibernate.ddl-auto=create

# Configuración Spring Security, usuario y password básicos.

  #security:
  #  user:
      #name: admin
      #password: 123